version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.10
    working_directory: ~/repo
        
    steps:
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . venv/bin/activate
            make install
            
            
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
        
            
	        
	        
